server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:springtest;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true